import { createSlice } from "@reduxjs/toolkit";
import data from "./product-data.json";

// Initial state for Redux store:
const initialState = {
  products: [data],
};

const productsSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    addProduct: (state, action) => {
      state.products = [...state.products, action.payload];
    },
    removeProduct: (state, action) => {
      state.products = state.products.filter((b) => b.id !== action.payload.id);
    },
  },
});

// Export actions generated by "createSlice()":
export const { addProduct, removeProduct } = productsSlice.actions;

// Export reducer generated by "createSlice()":
export default productsSlice.reducer;
